### PR TITLE
[Do Not Merge] Revert "Update Ruby version: 2.5.3 -> 2.6.0"

### PR DESCRIPTION
**Pull request by nanophate**
Revert "Update Ruby version: 2.5.3 -> 2.6.0"
This reverts commit 3deb4ae284f968143986e60a8775589924d7d6ef.

### CODE REVIEW

**Comment by yasulab** [comment]
Thanks for your PR ;) But we're glad if we could know why we need to downgrade Ruby version >< 💦

**Comment by nanophate** [comment]
Sorry for not informing the details for reverting to ruby 2.5.3. 🙇‍♂️

The reason behind doing this is related to Bundler becoming a default gem in ruby 2.6 and causing issues. Such as [efault/bundler-1.17.2.gemspec has no file list](https://bugs.ruby-lang.org/issues/15582), [`bundler` does not handle specified gem](https://bugs.ruby-lang.org/issues/15469).

As for not handling specified gem might cause an immediate issue as this project uses it.

https://github.com/yasslab/railsguides.jp/blob/3deb4ae284f968143986e60a8775589924d7d6ef/Gemfile#L24-L29

**Comment by nanophate** [comment]
Updating to ruby 2.6.1 might be a better option https://github.com/yasslab/railsguides.jp/tree/try_ruby_2_6_1 so I'll be closing this.

**Comment by yasulab** [comment]
Thanks for the note! And it seems nice to update Ruby to 2.6.1 later. ;) Let't try it our later. 😄

**Pull request closed without merging**
